---
# Create flannel directory
- name: Creating flannel directory
  file:
    path: /opt/bin
    state: directory

# Set up flannel
- name: Setting up flannel
  get_url:
    url: https://github.com/coreos/flannel/releases/download/v{{ version }}/flannel-{{ version }}-linux-amd64.tar.gz
    dest: /tmp
  environment:
    SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
- unarchive:
    copy: no
    creates: /opt/bin/flanneld
    dest: /tmp
    group: root
    owner: root
    src: /tmp/flannel-{{ version }}-linux-amd64.tar.gz
- command: mv /tmp/flannel-{{ version }}/flanneld /opt/bin
  args:
    creates: /opt/bin/flanneld
#- file:
#    path: /tmp/{{ item }}
#    state: absent
#  with_items:
#    - flannel-{{ version }}
#    - flannel-{{ version }}-linux-amd64.tar.gz

# Create flannel.service file
- name: Creating flannel.service file
  template:
    dest: /etc/systemd/system/flannel.service
    src: flannel.service.j2

# Start etcd2
- name: Starting flannel
  service:
    enabled: yes
    name: flannel.service
    state: started
