---
# Create Kubernetes Scheduler directory
- name: Creating Kubernetes Scheduler directory
  file:
    path: /srv/kubernetes/manifests
    state: directory

## Download Kubernetes Scheduler binary
#- name: Downloading Kubernetes Scheduler binary
#  get_url:
#    url: https://storage.googleapis.com/kubernetes-release/release/v{{ version }}/bin/linux/amd64/kube-scheduler
#    dest: /opt/bin/kube-scheduler
#    mode: a+x
#  environment:
#    SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt

# Create Kubernetes Scheduler manifest file
- name: Creating Kubernetes Scheduler manifest file
  template:
    dest: /srv/kubernetes/manifests/kube-scheduler.yml
    src: kube-scheduler.yml.j2

## Start Kubernetes Scheduler
#- name: Starting Kubernetes Scheduler
#  command: fleetctl destroy kube-scheduler.service
#  run_once: true
#- command: fleetctl start kube-scheduler.service
#  args:
#    chdir: /etc/systemd/system
#  run_once: true
