---
# Create EC2 VPC Security Group
- name: Creating EC2 {{ task_name }} Security Group
  ec2_group:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    description: "{{ security_group_description }}"
    name: "{{ security_group_name }}"
    region: "{{ region }}"
    rules: "{{ security_group_rules_ingress }}"
    rules_egress: "{{ security_group_rules_egress }}"
    vpc_id: "{{ vpc.vpc_id }}"
  register: security_group

- name: Tagging EC2 {{ task_name }} Security Group
  ec2_tag:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ region }}"
    resource: "{{ security_group.group_id }}"
    tags: "{{ security_group_tags }}"