---
# Create EC2 VPC Security Group
- name: Creating EC2 {{ item.task_name }} Security Group
  ec2_group:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    description: "{{ item.description }}"
    name: "{{ item.name }}"
    region: "{{ aws.region }}"
    rules: "{{ item.rules_ingress }}"
    rules_egress: "{{ item.rules_egress }}"
    vpc_id: "{{ vpc.vpc_id }}"
  with_items: aws.security_groups
  register: security_group

- name: Tagging EC2 {{ item.1.task_name }} Security Group
  ec2_tag:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws.region }}"
    resource: "{{ item.0.group_id }}"
    tags: "{{ item.1.tags }}"
  with_together:
    - security_group.results
    - aws.security_groups