---
# Create EC2 VPC Security Group
- name: Creating EC2 Security Groups
  ec2_group:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    description: "{{ item.description }}"
    name: "{{ item.name }}"
    region: "{{ aws.region }}"
    rules: "{{ item.rules_ingress }}"
    rules_egress: "{{ item.rules_egress }}"
    vpc_id: "{{ vpc_register.vpc_id }}"
  with_items: aws.security_groups
  register: security_group_register

- name: Tagging EC2 Security Groups
  ec2_tag:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    region: "{{ aws.region }}"
    resource: "{{ item.0.group_id }}"
    tags: "{{ item.1.tags }}"
  with_together:
    - security_group_register.results
    - aws.security_groups