---
admission_control: "{{ apiserver_admission_control }}"
advertise_address: "{{ apiserver_advertise_address }}"
allow_privileged: "{{ apiserver_allow_privileged }}"
bind_address: "{{ apiserver_bind_address }}"
client_ca_file: "{{ apiserver_client_ca_file }}"
cloud_provider: "{{ apiserver_cloud_provider }}"
etcd_servers: "{{ apiserver_etcd_servers }}"
insecure_bind_address: "{{ apiserver_insecure_bind_address }}"
insecure_port: "{{ apiserver_insecure_port }}"
secure_port: "{{ apiserver_secure_port }}"
service_account_key_file: "{{ apiserver_service_account_key_file }}"
service_cluster_ip_range: "{{ apiserver_service_cluster_ip_range }}"
tls_cert_file: "{{ apiserver_tls_cert_file }}"
tls_private_key_file: "{{ apiserver_tls_private_key_file }}"
version: "{{ apiserver_version }}"