---
# Create AWS Key Pair
- name: Creating AWS Key Pair
  ec2_key:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    key_material: "{{ aws.key_pair.material | default(omit) }}"
    name: "{{ aws.key_pair.name }}"
    region: "{{ aws.region }}"
    wait: "{{ aws.key_pair.wait }}"
