---
############### JAVA ###############
java_version: 7

############### ZOOKEEPER ###############
zookeeper_auto_purge_purge_interval: 12
zookeeper_auto_purge_snap_retain_count: 10000
zookeeper_client_port: 2181
zookeeper_init_limit: 10
zookeeper_java_heap_size_mb_percentage: 0.75
zookeeper_open_file_limit: 65536
zookeeper_sync_limit: 5
zookeeper_tick_time: 2000
zookeeper_version: 3.4.6

############### SUPERVISOR ###############
supervisor_http_server_port: 9001
supervisor_http_server_username: lmedina
supervisor_http_server_password: pass
supervisor_log_file_backups: 10
supervisor_log_file_max_bytes: 200MB
supervisor_start_retries: 999
supervisor_start_secs: 15
supervisor_std_err_log_file_backups: 10
supervisor_std_err_log_file_max_bytes: 200MB
supervisor_std_out_log_file_backups: 10
supervisor_std_out_log_file_max_bytes: 200MB
