---
# Create cloud-config
- name: Creating cloud-config
  template:
    src: cloud-config.yml.j2
    dest: /home/core/cloud-config.yml

# Apply cloud-config
- name: Applying cloud-config
  command: coreos-cloudinit --from-file=/home/core/cloud-config.yml