---
ansible_python_interpreter: /home/core/bin/python

coreos:
  docker:
    version: 1.8.2

  etcd:
    advertise_client_urls: http://{{ private_ip }}:4001
    data_dir: /var/lib/etcd2
    election_timeout: 1200
    initial_advertise_peer_urls: http://{{ private_ip }}:7001
    initial_cluster: "{% for host in groups['etcd'] %}{{ host | hash('md5') }}=http://{{ host }}:7001{%- if not loop.last -%},{%- endif %}{% endfor %}"
#    initial_cluster: "{{ private_ip | hash('md5') }}=internal-Etcd-543790002.us-west-2.elb.amazonaws.com:7001"
    initial_cluster_state: new
    listen_client_urls: http://{{ private_ip }}:4001,http://localhost:4001
    listen_peer_urls: http://{{ private_ip }}:7001,http://localhost:7001
    name: "{{ private_ip | hash('md5') }}"
    version: 2.2.0

  flannel:
    backend_type: vxlan
    etcd_endpoints: http://localhost:4001
    iface: "{{ private_ip }}"
    network_cidr: 10.2.0.0/16
    version: 0.5.3

  fleet:
    etcd_servers: http://localhost:4001
    version: 0.11.5

  python:
    version: 2.6.1