---
############### KUBERNETES ###############
kubernetes_service_cluster_ip: 10.3.0.1
kubernetes_version: 1.0.6

############### APISERVER ###############
apiserver_admission_control: NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota
apiserver_advertise_address: "{{ private_ip }}"
apiserver_allow_privileged: true
apiserver_bind_address: 0.0.0.0
apiserver_client_ca_file: /etc/kubernetes/ssl/ca.pem
apiserver_cloud_provider: aws
apiserver_etcd_servers: http://127.0.0.1:4001
apiserver_secure_port: 443
apiserver_service_account_key_file: /etc/kubernetes/ssl/apiserver-key.pem
apiserver_service_cluster_ip_range: 10.3.0.0/24
apiserver_tls_cert_file: /etc/kubernetes/ssl/apiserver.pem
apiserver_tls_private_key_file: /etc/kubernetes/ssl/apiserver-key.pem
apiserver_version: "{{ kubernetes_version }}"

############### CONTROLLER MANAGER ###############
controller_manager_cloud_provider: aws
controller_manager_master: http://127.0.0.1:8080
controller_manager_root_ca_file: /etc/kubernetes/ssl/ca.pem
controller_manager_service_account_private_key_file: /etc/kubernetes/ssl/apiserver-key.pem
controller_manager_version: "{{ kubernetes_version }}"

controller_manager_liveness_probe_initial_delay_secs: 15
controller_manager_liveness_probe_timeout_secs: 1
controller_manager_liveness_probe_http_get_host: 127.0.0.1
controller_manager_liveness_probe_http_get_path: /healthz
controller_manager_liveness_probe_http_get_port: 10252

############### SCHEDULER ###############
scheduler_master: http://127.0.0.1:8080
scheduler_version: "{{ kubernetes_version }}"

scheduler_liveness_probe_initial_delay_secs: 15
scheduler_liveness_probe_timeout_secs: 1
scheduler_liveness_probe_http_get_host: 127.0.0.1
scheduler_liveness_probe_http_get_path: /healthz
scheduler_liveness_probe_http_get_port: 10251

############### PROXY ###############
proxy_master: http://127.0.0.1:8080
proxy_privileged: true
proxy_version: "{{ kubernetes_version }}"

############### PODMASTER ###############
podmaster_controller_manager_dest_file: /dst/manifests/kube-controller-manager.yaml
podmaster_controller_manager_key: controller
podmaster_controller_manager_source_file: /src/manifests/kube-controller-manager.yaml
podmaster_etcd_servers: http://127.0.0.1:4001
podmaster_scheduler_dest_file: /dst/manifests/kube-scheduler.yaml
podmaster_scheduler_key: scheduler
podmaster_scheduler_source_file: /src/manifests/kube-scheduler.yaml
podmaster_version: 1.1
podmaster_whoami: "{{ private_ip }}"

############### KUBELET ###############
kubelet_allow_privileged: true
kubelet_api_servers: http://127.0.0.1:8080
kubelet_cadvisor_port: 0
kubelet_cloud_provider: aws
kubelet_cluster_dns: 10.3.0.10
kubelet_cluster_domain: cluster.local
kubelet_config: /etc/kubernetes/manifests
kubelet_hostname_override: "{{ private_ip }}"
kubelet_register_node: false
kubelet_version: "{{ kubernetes_version }}"
