---
kubernetes:
  apiserver:
    admission_control: NamespaceLifecycle,NamespaceExists,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota
    advertise_address: "{{ private_ip }}"
    allow_privileged: true
    bind_address: 0.0.0.0
    client_ca_file: /etc/kubernetes/ssl/ca.pem
    cloud_provider: aws
    etcd_servers: http://127.0.0.1:4001
    insecure_bind_address: 0.0.0.0
    insecure_port: 8080
    secure_port: 443
    service_account_key_file: /etc/kubernetes/ssl/apiserver-key.pem
    service_cluster_ip_range: 10.3.0.0/24
    tls_cert_file: /etc/kubernetes/ssl/apiserver.pem
    tls_private_key_file: /etc/kubernetes/ssl/apiserver-key.pem
    version: 1.1.1

  controller_manager:
    master: http://127.0.0.1:8080
    root_ca_file: /etc/kubernetes/ssl/ca.pem
    service_account_private_key_file: /etc/kubernetes/ssl/apiserver-key.pem
    version: 1.1.1

  kubelet:
    allow_privileged: true
    api_servers: http://127.0.0.1:8080
    cadvisor_port: 0
    cloud_provider: aws
    cluster_dns: 10.3.0.10
    cluster_domain: cluster.local
    config: /etc/kubernetes/manifests
    hostname_override: "{{ private_ip }}"
    register_node: false
    version: 1.1.1

  podmaster:
    controller_manager_dest_file: /dst/manifests/kube-controller-manager.yml
    controller_manager_key: controller
    controller_manager_source_file: /src/manifests/kube-controller-manager.yml
    etcd_servers: http://127.0.0.1:4001
    scheduler_dest_file: /dst/manifests/kube-scheduler.yml
    scheduler_key: scheduler
    scheduler_source_file: /src/manifests/kube-scheduler.yml
    version: 1.1
    whoami: "{{ private_ip }}"

  proxy:
    master: http://127.0.0.1:8080
    privileged: true
    version: 1.1.1

  scheduler:
    master: http://127.0.0.1:8080
    version: 1.1.1

  service_cluster_ip: 10.3.0.1