- name: Create {{ user }} and group
  shell: useradd -p "*" -U -m {{ user }} -G sudo
  ignore_errors: yes

#- name: Create test and group
#  shell: useradd -p "*" -U best -m test -G sudo

- name: Create test3 and group
  raw: useradd -p "*" -U -m test3 -G sudo

- name: Create test4 and group
  raw: sudo useradd -p "*" -U -m test4 -G sudo