# Create group
- name: Creating {{ group }} group
  group: name={{ group }} system=yes

# Create user
- name: Creating {{ user }} user
  user: name={{ user }} group={{ group }} shell=/bin/bash generate_ssh_key=yes system=yes

# Add user to sudoers
- name: Adding {{ user }} user to sudoers
  lineinfile: dest=/etc/sudoers line="{{ user }} ALL=NOPASSWD{{ ":" }} ALL"
