---
# Wiping $HOME directory
- name: Wiping $HOME directory
  raw: rm -rf /$HOME/*

# Set up Python
- name: Downloading Python
  raw: wget -N -P /tmp https://bitbucket.org/squeaky/portable-pypy/downloads/pypy-2.6.1-linux_x86_64-portable.tar.bz2

# Extract Python
- name: Extracting Python
  raw: tar xjf /tmp/pypy-2.6.1-linux_x86_64-portable.tar.bz2 -C /$HOME/
  
# Rename Python directory
- name: Renaming Python directory
  raw: mv /$HOME/pypy-2.6.1-linux_x86_64-portable /$HOME/python
  
# Create $HOME/bin directory
- name: Creating /$HOME/bin directory
  raw: mkdir -p /$HOME/bin
  
# Create symlink to Python executable
- name: Creating symlink to Python executable
  raw: ln -sf /$HOME/python/bin/pypy /$HOME/bin/python
  
# Clean up files
- name: Cleaning up
  raw: rm -r /tmp/pypy-2.6.1-linux_x86_64-portable.tar.bz2
