---
# Wiping /home/{{ remote_user }} directory
- name: Wiping /home/{{ remote_user }} directory
  raw: rm -rf /home/{{ remote_user }}/*

# Set up Python
- name: Downloading Python
  raw: wget -N -P /tmp https://bitbucket.org/squeaky/portable-pypy/downloads/pypy-2.6.1-linux_x86_64-portable.tar.bz2

# Extract Python
- name: Extracting Python
  raw: tar xjf /tmp/pypy-2.6.1-linux_x86_64-portable.tar.bz2 -C /home/{{ remote_user }}/
  
# Rename Python directory
- name: Renaming Python directory
  raw: mv /home/{{ remote_user }}/pypy-2.6.1-linux_x86_64-portable /home/{{ remote_user }}/python
  
# Create /home/{{ remote_user }}/bin directory
- name: Creating /home/{{ remote_user }}/bin directory
  raw: mkdir -p /home/{{ remote_user }}/bin
  
# Create symlink to Python executable
- name: Creating symlink to Python executable
  raw: ln -sf /home/{{ remote_user }}/python/bin/pypy /home/{{ remote_user }}/bin/python
  
# Clean up files
- name: Cleaning up
  raw: rm -r /tmp/pypy-2.6.1-linux_x86_64-portable.tar.bz2
