---
# Set up AWS environment
- name: AWS Setup
  connection: local
  gather_facts: no
  hosts: localhost

  vars_prompt:
    - name: aws_access_key
      prompt: "Enter your AWS access key"
      private: yes
    - name: aws_secret_key
      prompt: "Enter your AWS secret key"
      private: yes

  roles:
    - role: key_pair
    - role: vpc
    - role: security_group
    - role: iam
    - role: ec2

## Initial Kubernetes Setup
#- name: Initial Kubernetes Setup
#  gather_facts: no
#  hosts: kubernetes
#  remote_user: "{{ remote_user }}"
#  become: yes
#
#  roles:
#    - role: python
#    - role: openssl
#
## Kubernetes Master Setup
#- name: Kubernetes Master Setup
#  gather_facts: no
#  hosts: masters
#  remote_user: "{{ remote_user }}"
#  become: yes
#
#  roles:
#    - role: etcd
#    - role: flannel
#    - role: coreos/docker
#    - role: kube_apiserver
#    - role: kube_controller_manager
#    - role: kube_scheduler
#    - role: kube_podmaster
#    - role: kube_proxy
#    - role: kubelet





## Kubernetes Worker Setup
#- name: Kubernetes Worker Setup
#  gather_facts: no
#  hosts: workers
#  remote_user: "{{ remote_user }}"
#  sudo: yes
#
#  roles:
#    - role: etcd
#    - role: flannel
#    - role: coreos/docker
#    - role: kube_init

## Set up Ansible controller account
#- name: Ansible controller account setup
#  hosts: ec2
#  gather_facts: yes
#  sudo: yes
#  remote_user: "{{ remote_user }}"
#
#  roles:
#    - role: account
#      group: "{{ lookup('env', 'USER') }}"
#      user: "{{ lookup('env', 'USER') }}"
#
#  post_tasks:
#    - name: Adding "{{ lookup('env', 'USER') }}" SSH key to "{{ remote_user }}" user
#      authorized_key: user="{{ lookup('env', 'USER') }}" key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

# Set up ZooKeeper
#- name: ZooKeeper setup
#  hosts: zookeeper
#  remote_user: "{{ lookup('env', 'USER') }}"
#  sudo: yes
#
#  roles:
#    - { role: zookeeper, user: zookeeper, group: zookeeper }

# Set up Kafka
#- name: Kafka setup
#  hosts: kafka
#  remote_user: "{{ lookup('env', 'USER') }}"
#  sudo: yes
#
#  roles:
#    - { role: kafka, user: kafka, group: kafka }
