---
# Set up AWS environment
- name: AWS Setup
  connection: local
  gather_facts: no
  hosts: localhost

  vars_prompt:
    - name: aws_access_key
      prompt: "Enter your AWS access key"
      private: yes
    - name: aws_secret_key
      prompt: "Enter your AWS secret key"
      private: yes

  roles:
    - role: key_pair

    - role: vpc
      resource_tags: "{{ vpc_resource_tags }}"

    - role: security_group
      security_group_description: "{{ ssh_security_group_description }}"
      security_group_name: "{{ ssh_security_group_name }}"
      security_group_rules_ingress: "{{ ssh_security_group_rules_ingress }}"
      security_group_tags: "{{ ssh_security_group_tags }}"
      task_name: SSH

    - role: security_group
      security_group_description: "{{ ping_security_group_description }}"
      security_group_name: "{{ ping_security_group_name }}"
      security_group_rules_ingress: "{{ ping_security_group_rules_ingress }}"
      security_group_tags: "{{ ping_security_group_tags }}"
      task_name: Ping

    - role: security_group
      security_group_description: "{{ kubernetes_security_group_description }}"
      security_group_name: "{{ kubernetes_security_group_name }}"
      security_group_rules_ingress: "{{ kubernetes_security_group_rules_ingress }}"
      security_group_tags: "{{ kubernetes_security_group_tags }}"
      task_name: Kubernetes

    - role: security_group
      security_group_description: "{{ zookeeper_security_group_description }}"
      security_group_name: "{{ zookeeper_security_group_name }}"
      security_group_rules_ingress: "{{ zookeeper_security_group_rules_ingress }}"
      security_group_tags: "{{ zookeeper_security_group_tags }}"
      task_name: ZooKeeper

    - role: ec2
      ansible_public_ip_groups: "{{ master_ansible_public_ip_groups }}"
      ansible_private_ip_groups: "{{ master_ansible_private_ip_groups }}"
      count_tag: "{{ master_count_tag }}"
      ebs_optimized: "{{ master_ebs_optimized }}"
      exact_count: "{{ master_exact_count }}"
      security_groups: "{{ master_security_groups }}"
      instance_tags: "{{ master_instance_tags }}"
      instance_type: "{{ master_instance_type }}"
      task_name: Trident Master
      volumes: "{{ master_volumes }}"
      
    - role: ec2
      ansible_public_ip_groups: "{{ worker_ansible_public_ip_groups }}"
      ansible_private_ip_groups: "{{ worker_ansible_private_ip_groups }}"
      count_tag: "{{ worker_count_tag }}"
      ebs_optimized: "{{ worker_ebs_optimized }}"
      exact_count: "{{ worker_exact_count }}"
      security_groups: "{{ worker_security_groups }}"
      instance_tags: "{{ worker_instance_tags }}"
      instance_type: "{{ worker_instance_type }}"
      task_name: Trident Worker
      volumes: "{{ worker_volumes }}"

# Set up CoreOS
- name: CoreOS Master Setup
  hosts: master
  gather_facts: no
  sudo: yes
  remote_user: "{{ remote_user }}"

  roles:
    # - role: cloud_config
    - role: python
    - role: etcd
      etcd_proxy: off
    - role: fleet

# Set up CoreOS
- name: CoreOS Worker Setup
  hosts: worker
  gather_facts: no
  sudo: yes
  remote_user: "{{ remote_user }}"

  roles:
    # - role: cloud_config
    - role: python
    - role: etcd
      etcd_proxy: on
    - role: flannel
    - role: coreos/docker



## Set up Ansible controller account
#- name: Ansible controller account setup
#  hosts: ec2
#  gather_facts: yes
#  sudo: yes
#  remote_user: "{{ remote_user }}"
#
#  roles:
#    - role: account
#      group: "{{ lookup('env', 'USER') }}"
#      user: "{{ lookup('env', 'USER') }}"
#
#  post_tasks:
#    - name: Adding "{{ lookup('env', 'USER') }}" SSH key to "{{ remote_user }}" user
#      authorized_key: user="{{ lookup('env', 'USER') }}" key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

# Set up ZooKeeper
#- name: ZooKeeper setup
#  hosts: zookeeper
#  remote_user: "{{ lookup('env', 'USER') }}"
#  sudo: yes
#
#  roles:
#    - { role: zookeeper, user: zookeeper, group: zookeeper }

# Set up Kafka
#- name: Kafka setup
#  hosts: kafka
#  remote_user: "{{ lookup('env', 'USER') }}"
#  sudo: yes
#
#  roles:
#    - { role: kafka, user: kafka, group: kafka }
