---
# Create AWS Virtual Private Cloud
- name: Creating AWS Virtual Private Cloud
  ec2_vpc:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    cidr_block: "{{ cidr_block }}"
    dns_hostnames: "{{ dns_hostnames }}"
    dns_support: "{{ dns_support }}"
    instance_tenancy: "{{ instance_tenancy }}"
    internet_gateway: "{{ internet_gateway }}"
    region: "{{ region }}"
    resource_tags: "{{ vpc_resource_tags }}"
    route_tables: "{{ route_tables }}"
    subnets: "{{ subnets }}"
  register: vpc