---
# Create AWS Virtual Private Cloud
- name: Creating AWS Virtual Private Cloud
  ec2_vpc:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    cidr_block: "{{ aws.vpc.cidr_block }}"
    dns_hostnames: "{{ aws.vpc.dns_hostnames }}"
    dns_support: "{{ aws.vpc.dns_support }}"
    instance_tenancy: "{{ aws.vpc.instance_tenancy }}"
    internet_gateway: "{{ aws.vpc.internet_gateway }}"
    region: "{{ aws.region }}"
    resource_tags: "{{ aws.vpc.resource_tags }}"
    route_tables: "{{ aws.vpc.route_tables }}"
    subnets: "{{ aws.vpc.subnets }}"
  register: vpc