---
# Create Kubernetes Kubelet directory
- name: Creating Kubernetes Kubelet directory
  file:
    path: /opt/bin
    state: directory

# Download Kubernetes Kubelet binary
- name: Downloading Kubernetes Kubelet binary
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v{{ version }}/bin/linux/amd64/kubelet
    dest: /opt/bin/kubelet
    mode: a+x
  environment:
    SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt

# Create kubelet.service file
- name: Creating kubelet.service file
  template:
    dest: /etc/systemd/system/kubelet.service
    src: kubelet.service.j2

# Start Kubernetes Kubelet
- name: Starting Kubernetes Kubelet
  service:
    enabled: yes
    name: kubelet.service
    state: started