---
# Create cloud-config
- name: Creating cloud-config
  template:
    src: cloud-config.yml.j2
    dest: "{{ core_home_dir }}/cloud-config.yml"

# Apply cloud-config
- name: Applying cloud-config
  command: coreos-cloudinit --from-file={{ core_home_dir }}/cloud-config.yml
