---
# Create confd directories
- name: Creating confd directories
  file: 
    path: /opt/bin 
    state: directory
- file: 
    path: /etc/confd/conf.d 
    state: directory
- file: 
    path: /etc/confd/templates 
    state: directory

# Download confd
- name: Downloading confd
  get_url: 
    url: https://github.com/kelseyhightower/confd/releases/download/v0.10.0/confd-0.10.0-linux-amd64
    dest: /opt/bin
    force: yes
    mode: a+x
  environment:
    SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
    
# Rename confd executable
- name: Renaming confd executable
  command: mv /opt/bin/confd-0.10.0-linux-amd64 /opt/bin/confd
  args:
    creates: /opt/bin/confd
    
# [Unit]
# After=etcd2.service
# Description=Confd
# Requires=etcd2.service
# [Service]
# ExecStartPre=/usr/bin/mkdir -p /opt/bin
# ExecStartPre=/usr/bin/wget -O /opt/bin/confd https://github.com/kelseyhightower/confd/releases/download/v0.10.0/confd-0.10.0-linux-amd64
# ExecStartPre=/usr/bin/chmod +x /opt/bin/confd
# ExecStartPre=/usr/bin/mkdir -p /etc/confd
# ExecStart=/opt/bin/confd
# Restart=always
# [Install]
# WantedBy=multi-user.target
