---
# Create etcd directories
- name: Creating etcd directories
  file:
    path: /opt/bin
    state: directory

# Download etcd
- name: Downloading etcd
  get_url:
    url: https://github.com/coreos/etcd/releases/download/v2.2.0/etcd-v2.2.0-linux-amd64.tar.gz
    dest: /tmp
  environment:
    SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
- unarchive:
    copy: no
    dest: /tmp
    src: /tmp/etcd-v2.2.0-linux-amd64.tar.gz
- command: mv /tmp/etcd-v2.2.0-linux-amd64/etcd /opt/bin
- file:
    mode: a+x
    path: /opt/bin/etcd
    state: file
- file:
    name: /tmp/etcd-v2.2.0-linux-amd64.tar.gz
    state: absent

# Create etcd2.service file
- name: Creating etcd.service file
  template:
    src: etcd.service.j2
    dest: "{{ systemd_config_dir }}/etcd.service"

# Start etcd
- name: Starting etcd
  service:
    enabled: yes
    name: etcd2.service
    state: started
