---
# Create etcd directories
- name: Creating etcd directories
  file:
    path: /opt/bin
    state: directory

# Download etcd
- name: Downloading etcd
  get_url:
    url: https://github.com/coreos/etcd/releases/download/v2.2.0/etcd-v2.2.0-linux-amd64.tar.gz
    dest: /tmp
  environment:
    SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt
- unarchive:
    copy: no
    dest: /tmp
    group: root
    owner: root
    src: /tmp/etcd-v2.2.0-linux-amd64.tar.gz
- command: mv /tmp/etcd-v2.2.0-linux-amd64/etcd /tmp/etcd-v2.2.0-linux-amd64/etcdctl /opt/bin
- file:
    mode: a+x
    path: /opt/bin/etcd
    state: file
- command: /usr/bin/rm -rf /tmp/*

# Create etcd2.service file
- name: Creating etcd2.service file
  template:
    dest: "{{ systemd_config_dir }}/etcd2.service"
    src: etcd2.service.j2

# Start etcd2
- name: Starting etcd2
  service:
    enabled: yes
    name: etcd2.service
    state: started
