---
# Set up Python
- name: Python Setup
  raw: wget -N -P /tmp https://bitbucket.org/squeaky/portable-pypy/downloads/pypy-2.6.1-linux_x86_64-portable.tar.bz2
- raw: tar xjf /tmp/pypy-2.6.1-linux_x86_64-portable.tar.bz2 -C /home/core/
- raw: ln -s /home/core/pypy-2.6.1-linux_x86_64-portable/bin/pypy /home/core/python
- raw: rm -r /tmp/pypy-2.6.1-linux_x86_64-portable.tar.bz2

# Set Python interpreter
#- name: Setting Python interpreter
#  set_fact:
#    ansible_python_interpreter: /home/core/python
