---
# Create EC2 instance(s)
- name: Creating EC2 instance(s)
  ec2:
    assign_public_ip: "{{ item.assign_public_ip }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    count_tag: "{{ item.count_tag }}"
    ebs_optimized: "{{ item.ebs_optimized }}"
    exact_count: "{{ item.exact_count }}"
    group: "{{ item.security_groups }}"
    image: "{{ item.image }}"
    instance_profile_name: "{{ item.instance_profile_name | default(omit) }}"
    instance_tags: "{{ item.instance_tags }}"
    instance_type: "{{ item.instance_type }}"
    key_name: "{{ item.key_name }}"
    monitoring: "{{ item.monitoring }}"
    placement_group: "{{ item.placement_group | default(omit) }}"
    region: "{{ aws.region }}"
    user_data: "{{ item.user_data | default(omit) }}"
    volumes: "{{ item.volumes | default(omit) }}"
    vpc_subnet_id: "{{ vpc_register.subnets.0.id }}"
    wait: "{{ item.wait }}"
  with_items: aws.ec2
  register: ec2_register

# Wait for EC2 instance(s) to come up
- name: Waiting for EC2 instance(s) to come up
  wait_for:
    delay: 10
    host: "{{ item.1.public_ip }}"
    port: 22
    timeout: 300
  with_subelements:
    - ec2_register.results
    - tagged_instances

# Add new EC2 instance(s) to public Ansible groups
- name: Adding new EC2 instance(s) to public IP Ansible groups
  add_host:
    groups: "{{ item.0.item.ansible_public_ip_groups }}"
    name: "{{ item.1.public_ip }}"
    public_ip: "{{ item.1.public_ip }}"
    private_ip: "{{ item.1.private_ip }}"
  with_subelements:
    - ec2_register.results
    - tagged_instances

# Add new EC2 instance(s) to private Ansible groups
- name: Adding new EC2 instance(s) to private IP Ansible groups
  add_host:
    groups: "{{ item.0.item.ansible_private_ip_groups }}"
    name: "{{ item.1.private_ip }}"
    public_ip: "{{ item.1.public_ip }}"
    private_ip: "{{ item.1.private_ip }}"
  with_subelements:
    - ec2_register.results
    - tagged_instances

# Pause for SSH to come up
- name: Pausing for SSH to come up
  pause: seconds=5