---
# Create EC2 instance(s)
- name: Creating EC2 {{ task_name }} instance(s)
  ec2:
    assign_public_ip: "{{ assign_public_ip }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    count_tag: "{{ count_tag }}"
    ebs_optimized: "{{ ebs_optimized }}"
    exact_count: "{{ exact_count }}"
    group: "{{ security_groups }}"
    image: "{{ image }}"
    instance_tags: "{{ instance_tags }}"
    instance_type: "{{ instance_type }}"
    key_name: "{{ key_pair_name }}"
    monitoring: "{{ monitoring }}"
    placement_group: "{{ placement_group }}"
    region: "{{ region }}"
    user_data: "{{ user_data | default(omit) }}"
    volumes: "{{ volumes | default(omit) }}"
    vpc_subnet_id: "{{ vpc.subnets.0.id }}"
    wait: "{{ wait }}"
  register: ec2

# Wait for EC2 instance(s) to come up
- name: Waiting for EC2 {{ task_name }} instance(s) to come up
  wait_for: host="{{ item.public_ip }}" port=22 delay=10 timeout=300
  with_items: ec2.tagged_instances

# Add new EC2 instance(s) to Ansible groups
- name: Adding new {{ task_name }} EC2 instance(s) to public IP Ansible groups
  add_host: name="{{ item.public_ip }}" groups="{{ ansible_public_ip_groups }}" private_ip="{{ item.private_ip }}"
  with_items: ec2.tagged_instances

# Add new EC2 instance(s) to private Ansible groups
- name: Adding new {{ task_name }} EC2 instance(s) to private IP Ansible groups
  add_host: name="{{ item.private_ip }}" groups="{{ ansible_private_ip_groups }}" private_ip="{{ item.private_ip }}"
  with_items: ec2.tagged_instances

# Pause for SSH to come up
- name: Pausing for SSH to come up
  pause: seconds=5
