---
# Create Kubernetes API Server directory
- name: Creating Kubernetes API Server directory
  file:
    path: /opt/bin
    state: directory

# Download Kubernetes API Server binary
- name: Downloading Kubernetes API Server binary
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/release/v{{ version }}/bin/linux/amd64/kube-apiserver
    dest: /opt/bin/kube-apiserver
    mode: a+x
  environment:
    SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt

# Create kube-apiserver.service file
- name: Creating kube-apiserver.service file
  template:
    dest: /etc/systemd/system/kube-apiserver.service
    src: kube-apiserver.service.j2

# Start kube-apiserver
- name: Starting kube-apiserver
  service:
    enabled: yes
    name: kube-apiserver.service
    state: started