---
# Create IAM resource
- name: Creating IAM {{ iam_type }} resource
  iam:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    iam_type: "{{ iam_type }}"
    name: "{{ name }}"
    state: "{{ state }}"

# Add policy to IAM resrouce
- name: Adding policy to IAM resource
  iam_policy:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    iam_type: "{{ iam_type }}"
    iam_name: "{{ iam_name }}"
    policy_json: "{{ policy_json }}"
    policy_name: "{{ policy_name }}"
    state: "{{ state }}"
