---
############### KAFKA ###############
scala_version: "{{ kafka_scala_version }}"
kafka_version: "{{ kafka_kafka_version }}"
version: "{{ scala_version }}-{{ kafka_version }}"
archived_filename: kafka_{{ version }}.tgz
unarchived_filename: kafka_{{ version }}
kafka_url: http://www.us.apache.org/dist/kafka/{{ kafka_version }}/kafka_{{ version }}.tgz
slf4j_url: http://search.maven.org/remotecontent?filepath=org/slf4j/slf4j-nop/1.7.2/slf4j-nop-1.7.2.jar
download_location: /tmp
open_file_limit: "{{ kafka_open_file_limit }}"
disk_mount_dirs: [/log/1, /log/2, /log/3]
#disk_dirs: [/dev/sdb] # GCE
disk_dirs: [/dev/xvdb, /dev/xvdc, /dev/xvdd] # AWS
broker_id: "{{ hostvars[inventory_hostname].private_ip | regex_replace('\\.', '') | int % 2147483647 }}"

# Socket Server Settings
port: "{{ kafka_socket_server_port }}"
num_network_threads: "{{ kafka_num_network_threads }}"
num_io_threads: "{{ (ansible_devices | length - 1) * (groups['kafka'] | length) }}"
socket_send_buffer_bytes: "{{ kafka_socket_send_buffer_bytes }}"
socket_receive_buffer_bytes: "{{ kafka_socket_receive_buffer_bytes }}"
socket_request_max_bytes: "{{ kafka_socket_request_max_bytes }}"

# Log Basics
log_dirs: "{{ disk_mount_dirs | join(',') | regex_replace(',', '/kafka,') }}/kafka"
num_partitions: "{{ (ansible_devices | length - 1) * (groups['kafka'] | length) }}"
auto_leader_rebalance_enable: "{{ kafka_auto_leader_rebalance_enable }}"
default_replication_factor: "{{ groups['kafka'] | length }}"
num_replica_fetchers: "{{ kafka_num_replica_fetchers }}"
max_message_size_bytes: "{{ kafka_max_message_size_bytes }}"

# Log Flush Policy
log_flush_interval_messages: "{{ kafka_log_flush_interval_messages }}"
log_flush_interval_ms: "{{ kafka_log_flush_interval_ms }}"

# Log Retention Policy
log_retention_hours: "{{ kafka_log_retention_hours }}"
log_segment_bytes: "{{ kafka_log_segment_bytes }}"
log_retention_check_interval_ms: "{{ kafka_log_retention_check_interval_ms }}"

# ZooKeeper
zookeeper_connect: "{{ groups['zookeeper_private'] | join(',') | regex_replace(',', ':2181,') }}:2181"
zookeeper_connection_timeout_ms: "{{ kafka_zookeeper_connection_timeout_ms }}"

# Shutdown Policy
controlled_shutdown_enable: "{{ kafka_controlled_shutdown_enable }}"
controlled_shutdown_max_retries: "{{ kafka_controlled_shutdown_max_retries }}"
controlled_shutdown_retry_backoff_ms: "{{ kafka_controlled_shutdown_retry_backoff_ms }}"

############### SUPERVISOR ###############
auto_start: "true"
auto_restart: "true"
command: /opt/kafka/{{ version }}/bin/kafka-server-start.sh ../config/server.properties
directory: /opt/kafka/{{ version }}/bin
log_file: /var/log/supervisor/supervisord.log
log_file_backups: "{{ supervisor_log_file_backups }}"
log_file_max_bytes: "{{ supervisor_log_file_max_bytes }}"
start_retries: "{{ supervisor_start_retries }}"
start_secs: "{{ supervisor_start_secs }}"
std_err_log_file: /var/log/kafka/kafka_supervisor_err.log
std_err_log_file_backups: "{{ supervisor_std_err_log_file_backups }}"
std_err_log_file_max_bytes: "{{ supervisor_std_err_log_file_max_bytes }}"
std_out_log_file: /var/log/kafka/kafka_supervisor_out.log
std_out_log_file_backups: "{{ supervisor_std_out_log_file_backups }}"
std_out_log_file_max_bytes: "{{ supervisor_std_out_log_file_max_bytes }}"
stop_as_group: "true"