---

# Create new certificate authority
- name: Creating new certificate authority
#  local_action:
#    module: command
#    free_form: openssl genrsa -out ca-key.pem 2048
#    args:
#        chdir: /tmp

#  local_action:
#    module: command openssl genrsa -out /tmp/ca-key.pem 2048
#    args:
#      chdir: /tmp
#
  local_action: command openssl genrsa -out ca-key.pem 2048
  args:
    chdir: /tmp

- file:
    path: /tmp/*
    state: absent
