---
# Check for apt-transport-https
- name: Checking if "{{ https_path }}"
  stat: path={{ https_path }}
  register: https

# Install apt-transport-https only if necessary
- apt: name=apt-transport-https update_cache=yes state=latest
  when: https.stat.exists == false

# Add Docker repository key
- name: Adding Docker repository key
  apt_key: id={{ key_id }} keyserver={{ key_server }}

# Add Docker repository
- name: Adding Docker repository
  apt_repository: repo="{{ repository }}"

# Install Docker
- name: Installing Docker
  apt: name=lxc-docker update_cache=yes state=latest
