---
# Create Kubernetes Controller Manager directory
- name: Creating Kubernetes Controller Manager directory
  file:
    path: /etc/kubernetes/manifests
    state: directory

## Download Kubernetes Controller Manager binary
#- name: Downloading Kubernetes Controller Manager binary
#  get_url:
#    url: https://storage.googleapis.com/kubernetes-release/release/v{{ version }}/bin/linux/amd64/kube-controller-manager
#    dest: /opt/bin/kube-controller-manager
#    mode: a+x
#  environment:
#    SSL_CERT_FILE: /etc/ssl/certs/ca-certificates.crt

# Create Kubernetes Controller Manager manifest file
- name: Creating Kubernetes Controller Manager manifest file
  template:
    dest: /etc/kubernetes/manifests/kube-controller-manager.yml
    src: kube-controller-manager.yml.j2

## Start Kubernetes Controller Manager
#- name: Starting Kubernetes Controller Manager
#  command: fleetctl destroy kube-controller-manager.service
#  run_once: true
#- command: fleetctl start kube-controller-manager.service
#  args:
#    chdir: /etc/systemd/system
#  run_once: true